### ISSUE TITLE
Can't resolve 'idx' in InnerList.js

### ISSUE THREAD

**Issue by kohchihao** [lucasbesen/react-kanban-dnd#17]
Hi,
I am looking to try out this library. However, when i try to set it up, it shows me this warning.

```
./node_modules/react-kanban-dnd/lib/InnerList.js
Module not found: Can't resolve 'idx' in '/node_modules/react-kanban-dnd/lib'
```

**Comment by kohchihao** [comment]
After looking at the library `package.json`, I think the library `idx` should be inside `dependencies` instead of `devDependencies` ?

**Comment by lucasbesen** [comment]
Fixed it on: https://github.com/lucasbesen/react-kanban-dnd/pull/18
